### PR TITLE
#231-update item-descr fw

### LINKED ISSUE #231: [Home page] The item descriptions are bold in the home page “How it works” block.
The item descriptions are bold in the home page “How it works” block. The issue is reproduced with the student and tutor registration options.

**Environment:** Windows 10 x64
Microsoft Edge 112.0.1722.48
Google Chrome 112.0.5615.122
MacOS Big Sur 11.7.3
Safari 16.3 (16614.4.6.11.6, 16614)

**Reproducible**: always.

**Preconditions:**
The user is not logged in.

**Steps to reproduce:**
1. Open the site.
2. Click on the “How it works” button on the home page header.
3. Take a look at the home page “How it works” block.

**Actual result:**
The item descriptions are bold in the home page “How it works” block.

**Expected result**
The item descriptions in the home page “How it works” block are corresponded to the mockup.

### PR DESCRIPTION
**Pull request by Makarenko23**
updated item description font-weight, changing variant style from 'subtitle2' to 'body2'.

previous result: 
image
actual result:
image

### CODE REVIEW

**Review by Zorro769 — APPROVED** [review]
Looks good for me

File: src/containers/guest-home-page/cards-with-button/CardsWithButton.tsx [hunk 1]
```diff
@@ -50,7 +51,11 @@ const CardsWithButton: FC<CardsWithButtonProps> = ({
             <Box className='dots' component='img' src={dots} />
           </Box>
           <TitleWithDescription
-            description={t(item.description)}
+            description={
+              <Typography variant='body2'>
+                {t(item.description as string)}
```
Comment (vlad-khrychov) [inline src/containers/guest-home-page/cards-with-button/CardsWithButton.tsx]: Here we can receive undefined, because we have a type like this 
```
export interface AccordionItem {
  title: string
  description?: string
  content?: ReactNode
}
```
Maybe better to add some conditional replacement?
```suggestion
                {t(item.description || "")}
```

**Review by vlad-khrychov — APPROVED** [review]
